### ISSUE TITLE
Removing join() breaks moreorg

### ISSUE THREAD

**Issue by m0rsch1** [rock-knowledge-reasoning/knowledge-reasoning-owlapi#1]
The commit ef78b126eeb0a570889a28c98a2c1166d4e67431 breaks [moreorg](https://github.com/rock-knowledge-reasoning/knowledge-reasoning-moreorg)

**Comment by 2maz** [comment]
This is fixed for moreorg now, forgot to push a commit on moreorg. Thx for reporting.
